name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v2.1.0
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.4.0
      with:
        node-version: 14.17.*
    - name: Restore dependencies
      run: npm install
    - name: Test
      run: npm test
